"""empty message

Revision ID: 5e18878de307
Revises: b0965b49c24f
Create Date: 2022-05-26 15:13:59.771644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e18878de307'
down_revision = 'b0965b49c24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    op.drop_column('groups', 'hidden')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('hidden', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    # ### end Alembic commands ###
